kind: pipeline
type: docker
name: default

steps:
- name: display go version
  image: golang
  pull: if-not-exists
  commands:
  - go version
  - git config --global pack.windowMemory "100m"
  - git config --global pack.packSizeLimit "100m"
  - git config --global pack.threads "1"
  - git config --list
